version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: webservice-db
    environment:
      POSTGRES_DB: webservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1511
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: webservice-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/webservice
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1511
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: webservice-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  postgres_data:
